image:
  name: jdsutton7/compute-node

before_script:
  - make install
  
install_and_build:
  script:
    - make test
  
pages:
  stage: deploy
  script:
  - mkdir .public
  - cp -r ./gl_pages/* .public
  - make build .public
  artifacts:
    paths:
    - public
